////----------------------------------------------------------------------
//// This file has been automatically generated by
//// VerifStudio Software Version 0.63, Accelver Systems Inc.
//// Any modifications that you make to this file may be
//// overwritten by the tool when regenerating the files. 
////----------------------------------------------------------------------

`ifndef AHB_MASTER_TRANSACTION__SV
`define AHB_MASTER_TRANSACTION__SV

class ahb_master_transaction#(AHB_ADDR_WIDTH=16,AHB_DATA_WIDTH=16) extends uvm_sequence_item;
	
	rand bit [AHB_ADDR_WIDTH-1:0] m_address;

	rand ahb_read_write_e m_read_write;
	
	rand bit [AHB_DATA_WIDTH-1:0] m_rdata;

	rand bit [AHB_DATA_WIDTH-1:0] m_wdata;

	  ahb_response_e m_response_type;

	  ahb_transfer_type_enum m_transfer_type;

	  ahb_burst_type_enum m_burst_type;

    // Register the class ahb_master_transaction with the factory.
    `uvm_object_param_utils_begin(ahb_master_transaction#(AHB_ADDR_WIDTH,AHB_DATA_WIDTH))
    	`uvm_field_int(m_address, UVM_ALL_ON)
	`uvm_field_enum(ahb_read_write_e, m_read_write, UVM_ALL_ON)
	`uvm_field_int(m_rdata, UVM_ALL_ON)
	`uvm_field_enum(ahb_response_e , m_response_type, UVM_ALL_ON)
	`uvm_field_enum(ahb_transfer_type_enum, m_transfer_type, UVM_ALL_ON)
	`uvm_field_enum(ahb_burst_type_enum, m_burst_type , UVM_ALL_ON)
    `uvm_object_utils_end

    // The Constructor for this Class.
    function new(string name="ahb_master_transaction");
        super.new(name);
    endfunction: new

endclass: ahb_master_transaction

`endif
